### Input configuration
#
# Read `man 5 sway-input` for more information about this section.

# Touchpad configuration
input type:touchpad {
    dwt enabled
    tap enabled
    natural_scroll enabled
}

# Keyboard configuration
input type:keyboard {
    xkb_numlock enabled
    xkb_layout us
    xkb_variant intl
}
