# swaybar

bar {
    font pango: Hack Nerd Font 11
    position top
    workspace_buttons yes
    tray_output *
    status_command i3status-rs ~/.config/i3status-rust/config.toml

    colors {
        background  #2c2c2e
        statusline  #f5f5f7
        separator   #48484a

        focused_workspace  #0a84ff #0a84ff #ffffff
        active_workspace   #3a3a3c #3a3a3c #f5f5f7
        inactive_workspace #2c2c2e #2c2c2e #a1a1a6
        urgent_workspace   #ff453a #ff453a #ffffff
    }
}
