[main]
font=Hack Nerd Font:size=11
initial-color-theme=dark

[colors-dark]
foreground=f0e5ff
background=1a0026

cursor=1a0026 3c84f7
selection-foreground=ffffff
selection-background=3c84f7

# black
regular0=000000

# red
regular1=c91b00

# green
regular2=00c200

# yellow
regular3=c7c400

# blue
regular4=0225c7

# magenta
regular5=c930c7

# cyan
regular6=00c5c7

# white / gray
regular7=c7c7c7

# bright black / gray
bright0=686868

# bright red
bright1=ff6e67

# bright green
bright2=5ffa68

# bright yellow
bright3=fffc67

# bright blue
bright4=6871ff

# bright magenta
bright5=ff77ff

# bright cyan
bright6=60fdff

# bright white
bright7=ffffff
